# On-target and off-target

## Merge profiling

``` {r eval = TRUE, fig.width = 10, fig.height = 4}

tp53.targets <- read.xlsx("suppdata/p53_targets.xlsx")
rownames(tp53.targets) <- tp53.targets$Gene

tp53.target.g32 <- tp53.targets$Gene[which(tp53.targets$LiteratureNum >= 10)]
tp53.target.g116 <- tp53.targets$Gene

merge.meta.data <- read.xlsx("suppdata/p53_meta.xlsx", sheet = 1)

merge.compare.data <- read.xlsx("/Users/daiyuting/Documents/projects/tp53/paper/activity/2023-06-25\ compounds/TableS1-Related-to-Figure2A.xlsx", sheet = 1, startRow = 2)
merge.compare.data$Sample <- merge.compare.data$`Sample.name.(after.treatment)`
merge.compare.data$Control <- merge.compare.data$`Sample.name.(untreated.samples)`
merge.compare.data$Group <- str_replace(merge.compare.data$Sample, regex("_rep.$"), "")
rownames(merge.compare.data) <- merge.compare.data$`Sample.name.(after.treatment)`

merge.mat <- read.xlsx("/Users/daiyuting/Documents/projects/tp53/paper/activity/2023-06-25\ compounds/TableS1-Related-to-Figure2A.xlsx", sheet = 2, startRow = 3, rowNames = T)
```


## Normalization

``` {r eval = TRUE, fig.width = 10, fig.height = 4}

# Median normalization
merge.nor.mat <- merge.mat
sub.1 <- aggregate(colMedians(as.matrix(merge.nor.mat)), 
                   list(Cell = merge.meta.data$Dataset), min)
for (i in 1:ncol(merge.nor.mat)) {
  merge.nor.mat[, i] <- merge.nor.mat[, i] - sub.1$x[which(sub.1$Cell == merge.meta.data$Dataset[i])]
}


# Generation of fold change (Log2-transformed for FPKM) of cell line samples after treatment compared to before treatment 
compare.mat <- NULL
for (i in 1:nrow(merge.compare.data)) {
  if (length(grep("; ", merge.compare.data$Control[i])) > 0) {
    sub.1 <- unlist(str_split(merge.compare.data$Control[i], "; "))
    sub <- merge.nor.mat[, merge.compare.data$Sample[i]] - rowMeans(merge.nor.mat[, sub.1])
  } else {
    sub <- merge.nor.mat[, merge.compare.data$Sample[i]] - merge.nor.mat[, merge.compare.data$Control[i]]
  }
  compare.mat <- cbind(compare.mat, sub)
}
colnames(compare.mat) <- merge.compare.data$Sample


```

## 32 confident p53 targets

Related to Fig. 1a.

``` {r eval = TRUE, fig.width = 10, fig.height = 6}

my.breaks <- c(seq(-1.5, -0.01, by = 0.001), seq(0.01, 1.5, by = 0.001) ) 
my.colors <- c(colorRampPalette(colors = c("#00599F","#00599F","#287dba","#62aee5","#a8dcff","white"))(length(my.breaks)/2), 
               colorRampPalette(colors = c("white","#ffca79","#ef6e51","#db1b18","#b50600","#b50600"))(length(my.breaks)/2))

plot.mat <- compare.mat[tp53.target.g32, ]
anno.data <- data.frame(row.names = merge.compare.data$Sample, 
                        Mutant = merge.compare.data$p53.status)
p <- pheatmap(plot.mat, scale = "none",
              color = my.colors, breaks = my.breaks,
              cluster_row = F, cluster_col = F, border_color = NA,
              annotation_col = anno.data, 
              annotation_colors = anno.color,
              clustering_method = "ward.D2",
              clustering_distance_rows = "manhattan",
              clustering_distance_cols = "manhattan",
              fontsize_col = 8,
              fontsize_row = 6)
p


plot.mat <- compare.mat[!rownames(compare.mat) %in% tp53.target.g32, ]
p <- pheatmap(plot.mat, scale = "none",
              color = my.colors, breaks = my.breaks,
              cluster_row = F, cluster_col = F, border_color = NA,
              annotation_col = anno.data, 
              annotation_colors = anno.color,
              clustering_method = "ward.D2",
              clustering_distance_rows = "manhattan",
              clustering_distance_cols = "manhattan",
              fontsize_col = 8,
              fontsize_row = 0.1)
p

```


## 116 p53 targets

Related to Extended Data Fig. 1a.

``` {r eval = TRUE, fig.width = 10, fig.height = 6}

my.breaks <- c(seq(-1.5, -0.01, by = 0.001), seq(0.01, 1.5, by = 0.001) ) 
my.colors <- c(colorRampPalette(colors = c("#00599F","#00599F","#287dba","#62aee5","#a8dcff","white"))(length(my.breaks)/2), 
               colorRampPalette(colors = c("white","#ffca79","#ef6e51","#db1b18","#b50600","#b50600"))(length(my.breaks)/2))

plot.mat <- compare.mat[tp53.target.g116, ]
anno.data <- data.frame(row.names = merge.compare.data$Sample, Mutant = merge.compare.data$p53.status)
p <- pheatmap(plot.mat, scale = "none",
              color = my.colors, breaks = my.breaks,
              cluster_row = F, cluster_col = F, border_color = NA,
              annotation_col = anno.data, 
              annotation_colors = anno.color,
              clustering_method = "ward.D2",
              clustering_distance_rows = "manhattan",
              clustering_distance_cols = "manhattan",
              fontsize_col = 8,
              fontsize_row = 2)
p


plot.mat <- compare.mat[!rownames(compare.mat) %in% tp53.target.g116, ]
p <- pheatmap(plot.mat, scale = "none",
              color = my.colors, breaks = my.breaks,
              cluster_row = F, cluster_col = F, border_color = NA,
              annotation_col = anno.data, 
              annotation_colors = anno.color,
              clustering_method = "ward.D2",
              clustering_distance_rows = "manhattan",
              clustering_distance_cols = "manhattan",
              fontsize_col = 8,
              fontsize_row = 0.1)
p

```


### On-target and off-target score

Related to Extended Data Fig. 1c and 1d.

``` {r eval = TRUE, fig.width = 20, fig.height = 4}

plot.order <- c("U937_WT","U937_L130V_ATO","U937_L130F_ATO","U937_L130R_ATO","U937_P142L_ATO","U937_V143M_ATO","U937_M237V_ATO","U937_F270I_ATO","U937_F270V_ATO","U937_V272A_ATO","U937_V272M_ATO","U937_V272M_PAT","Kasumi-1_R248Q_Kevetrin_6h","SKM1_R248Q_APR-246","staET7.1_R273H_APR-246","staET7.2_R273H_APR-246","staET7.3_R273H_APR-246","Saos-2_R273H_APR-246_6h","Saos-2_R273H_APR-246_12h","Kasumi-1_R248Q_Kevetrin_48h","PCI13_G245D_COTI-2","U266_A161T_PRIMA-1","U937_R273H_ATO","U937_R273H_PAT","PCI13_G245D_CDDP","8266R5_null_PRIMA-1","Saos-2_null_APR-246_6h","Saos-2_null_APR-246_12h")

total.onoff <- NULL
total.test.cutoff <- c(1.2, 1.4, 1.5, 1.6, 1.8, 2.0)

for (i in 1:length(total.test.cutoff)) {
  
  cutoff_tmp <- round(log2(total.test.cutoff[i]), 2)
  plot.data <- data.frame(Sample = colnames(compare.mat),
                          UP_116 = colSums(compare.mat[tp53.target.g116, ] > cutoff_tmp) ,
                          UP_32 = colSums(compare.mat[tp53.target.g32, ] > cutoff_tmp),
                          UP_other_116 = colSums(compare.mat[!rownames(compare.mat) %in% tp53.target.g116, ] > cutoff_tmp) ,
                          UP_other_32 = colSums(compare.mat[!rownames(compare.mat) %in% tp53.target.g32, ] > cutoff_tmp) )
  plot.data$Mutant <- merge.compare.data$p53.status[match(plot.data$Sample, merge.compare.data$Sample)]
  plot.data$MutantType <- "MUT"
  plot.data$MutantType[which(plot.data$Mutant == "WT")] <- "WT"
  
  plot.data$ON_target_32 <- (plot.data$UP_32) / (plot.data$UP_other_32 + plot.data$UP_32) / (32/18296)
  plot.data$ON_target_116 <- (plot.data$UP_116) / (plot.data$UP_other_116 + plot.data$UP_116) / (116/18296)
  plot.data$OFF_target_32 <- plot.data$UP_other_32 / (plot.data$UP_other_32 + plot.data$UP_32) / ((18296-32)/18296)
  plot.data$OFF_target_116 <- plot.data$UP_other_116 / (plot.data$UP_other_116 + plot.data$UP_116) / ((18296-116)/18296)
  plot.data$Group <- merge.compare.data$Group[match(plot.data$Sample, merge.compare.data$Sample)]
  
  plot.data$ON_target_32[which(is.na(plot.data$ON_target_32))] = 1
  plot.data$ON_target_116[which(is.na(plot.data$ON_target_116))] = 1
  plot.data$OFF_target_32[which(is.na(plot.data$OFF_target_32))] = 1
  plot.data$OFF_target_116[which(is.na(plot.data$OFF_target_116))] = 1
  
  plot.data.group <- aggregate(plot.data[, c("ON_target_32","ON_target_116","OFF_target_32","OFF_target_116")], list(Sample = plot.data$Group), mean)
  plot.data.group <- plot.data.group[match(plot.order, plot.data.group$Sample), ]
  plot.data.group$Mutant <- merge.compare.data$p53.status[match(plot.data.group$Sample, merge.compare.data$Sample)]
  plot.data.group$MutantType <- "MUT"
  plot.data.group$MutantType[which(plot.data.group$Mutant == "WT")] <- "WT"

  if (i < 6) {
    group.tag <- paste0("FC_", total.test.cutoff[i] )
  } else {
    group.tag <- "FC_2.0"
  }
  
  plot.data.group$Group <- group.tag

  total.onoff <- rbind(total.onoff, plot.data.group)
}

total.onoff$Group <- factor(as.character(total.onoff$Group), levels = c("FC_1.2","FC_1.4","FC_1.5","FC_1.6","FC_1.8","FC_2.0"))

p <- ggdotchart(total.onoff, x = "Sample", y = "ON_target_32",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("32 confident p53 targets"), 
                xlab = "", ylab = "On-target score",
                palette = c("black","red"), width = 0.6,
                dot.size = 2 )
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 4))
p <- p + scale_y_continuous(breaks = c(0,1,16,32,48,64), 
                            labels = c(0,1,16,32,48,64), limits = c(0,64) )
p <- p + facet_wrap( ~ Group, ncol = 6)
p


p <- ggdotchart(total.onoff, x = "Sample", y = "OFF_target_32",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("32 confident p53 targets"), 
                xlab = "", ylab = "Off-target score",
                palette = c("black","red"), width = 0.6,
                dot.size = 2 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 4))
p <- p + scale_y_continuous(limits = c(0.80, 1.05))
p <- p + facet_wrap( ~ Group, ncol = 6)
p

p <- ggdotchart(total.onoff, x = "Sample", y = "ON_target_116",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("116 p53 targets"), 
                xlab = "", ylab = "On-target score",
                palette = c("black","red"), width = 0.6,
                dot.size = 2 )
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 4))
p <- p + scale_y_continuous(breaks = c(0,1,16,32,48,64), 
                            labels = c(0,1,16,32,48,64), limits = c(0,64) )
p <- p + facet_wrap( ~ Group, ncol = 6)
p


p <- ggdotchart(total.onoff, x = "Sample", y = "OFF_target_116",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("116 p53 targets"), 
                xlab = "", ylab = "Off-target score",
                palette = c("black","red"), width = 0.6,
                dot.size = 2 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 4))
p <- p + scale_y_continuous(limits = c(0.80, 1.05))
p <- p + facet_wrap( ~ Group, ncol = 6)
p

```


### Using cutoff FC 1.5

Related to Fig. 1c.

``` {r eval = TRUE, fig.width = 9, fig.height = 5}

total.onoff.sub <- total.onoff[which(total.onoff$Group == "FC_1.5"), ]

p <- ggdotchart(total.onoff.sub, x = "Sample", y = "ON_target_32",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("32 confident p53 targets"), 
                xlab = "", ylab = "On-target score",
                palette = c("black","red"),
                dot.size = 4 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 10))
p <- p + scale_y_continuous(limits = c(-0.5,16), breaks = c(0,1,4,8,12,16))
p

p <- ggdotchart(total.onoff.sub, x = "Sample", y = "OFF_target_32",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("32 confident p53 targets"), 
                xlab = "", ylab = "Off-target score",
                palette = c("black","red"),
                dot.size = 4 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 10))
p <- p + scale_y_continuous(limits = c(0.95,1.005))
p

p <- ggdotchart(total.onoff.sub, x = "Sample", y = "ON_target_116",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("116 p53 targets"), 
                xlab = "", ylab = "On-target score",
                palette = c("black","red"),
                dot.size = 4 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 10))
p <- p + scale_y_continuous(limits = c(-0.5,12), breaks = c(0,1,4,8,12))
p

p <- ggdotchart(total.onoff.sub, x = "Sample", y = "OFF_target_116",
                color = "MutantType", sorting = "none", shape = 16,
                order = plot.order,
                main = paste0("116 p53 targets"), 
                xlab = "", ylab = "Off-target score",
                palette = c("black","red"),
                dot.size = 4 ) + theme_few()
p <- p + geom_hline(yintercept = 1, linetype = 2, color = "black")
p <- p + theme_base() + theme(plot.background = element_blank())
p <- p + theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5, size = 10))
p <- p + scale_y_continuous(limits = c(0.92,1.01))
p

```














